apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: maharati
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dhouhaaoui/frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: maharati
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: frontend
