apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: maharati
data:
  init.sql: |
    -- Table des rôles
    CREATE TABLE IF NOT EXISTS roles (
      id INT PRIMARY KEY AUTO_INCREMENT,
      name VARCHAR(255)
    );
    -- Table des utilisateurs
    CREATE TABLE IF NOT EXISTS Users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL,
      username VARCHAR(255),
      address VARCHAR(255),
      phone VARCHAR(20),
      profile_image VARCHAR(255)
    );
    -- Table des rôles des utilisateurs
    CREATE TABLE IF NOT EXISTS user_roles (
      userId INT,
      roleId INT,
      PRIMARY KEY (userId, roleId),
      FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE
    );
    -- Table des services
    CREATE TABLE IF NOT EXISTS Services (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(255),
      description TEXT,
      category VARCHAR(100),
      price DECIMAL(10, 2),
      availability ENUM('available', 'not_available') DEFAULT 'available',
      ratings DECIMAL(3, 2),
      image VARCHAR(255)
    );
    -- Table des fournisseurs
    CREATE TABLE IF NOT EXISTS Providers (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      phone VARCHAR(20) NOT NULL,
      address VARCHAR(255) NOT NULL,
      services_offered TEXT,
      ratings DECIMAL(3, 2),
      availability ENUM('available', 'busy') DEFAULT 'available',
      image VARCHAR(255)
    );
    -- Table des réservations
    CREATE TABLE IF NOT EXISTS Bookings (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT,
      service_id INT,
      date DATE,
      time TIME,
      status ENUM('pending', 'confirmed', 'cancelled') DEFAULT 'pending',
      FOREIGN KEY (user_id) REFERENCES Users(id),
      FOREIGN KEY (service_id) REFERENCES Services(id)
    );
    -- Table des commentaires
    CREATE TABLE IF NOT EXISTS Comments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT,
      service_id INT,
      commentTEXT TEXT,
      rating DECIMAL(3, 2),
      FOREIGN KEY (user_id) REFERENCES Users(id),
      FOREIGN KEY (service_id) REFERENCES Services(id)
    );
