apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: maharati
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MDAwMA==
  MYSQL_DATABASE: dGVzdGRi
  MYSQL_USER: ZGhvdWhh
  MYSQL_PASSWORD: MDAwMA==
